/* Generated by `ACE.Content.Tools configdefaults --write --migration-name=...`.

   WHY THIS FILE EXISTS. PropertyManager.LoadDefaultProperties calls ModifyBool/ModifyDouble/
   ModifyLong/ModifyString for every code default on every boot, and each call marks the entry
   Modified, so the first background flush (every 5 minutes) writes EVERY code default to
   ace_shard.config_properties_* as a row on that shard. From then on the persisted row wins
   over the code default (PropertyManager.LoadPropertiesFromDB runs after LoadDefaultProperties
   and overwrites the in-memory cache), so simply changing a `new Property<T>(default, ...)`
   value in source never reaches a shard that already has a row for that key. This file moves
   the persisted rows forward to match the new code defaults below.

   THE GUARD DELIBERATELY LEAVES HAND-TUNED ROWS ALONE. Each UPDATE below only touches a row
   whose current value still equals the OLD default this migration is moving away from. A row
   an operator has since hand-tuned to some other value (via /modifydouble or similar) does not
   match that guard and is left untouched - this migration is about rows that are still sitting
   on the old code default, not about overwriting deliberate configuration.

   RE-RUNNING IS A NO-OP. Once a row has been moved to the new default, its value no longer
   matches the guard's old-value condition, so applying this file again (or against a shard
   that never had the key at all, in which case the WHERE clause simply matches zero rows)
   changes nothing. No marker table or applied-updates bookkeeping is needed for that reason.

   A HAND-ADDED OR ON THE GUARD IS ALLOWED when the repo owner rules that some other specific
   tuned value should also move to the new default - add `OR <condition-on-value>` inside the
   guard's parentheses for that one statement, with a comment above it citing the ruling and
   its date. Do not do this without an explicit owner ruling; the default posture is to leave
   tuned rows alone. */

UPDATE `config_properties_double` SET `value` = 0.095 WHERE `key` = 'class_ability_deadeye_percent_per_rank' AND ABS(`value` - 0.08) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.06 WHERE `key` = 'class_ability_dispellingedge_chance_step' AND ABS(`value` - 0.05) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.115 WHERE `key` = 'class_ability_empoweredsummons_percent_per_rank' AND ABS(`value` - 0.1) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.07 WHERE `key` = 'class_ability_executioner_percent_per_rank' AND ABS(`value` - 0.04) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.095 WHERE `key` = 'class_ability_overchannel_percent_per_rank' AND ABS(`value` - 0.08) < 1e-9;
UPDATE `config_properties_double` SET `value` = 12 WHERE `key` = 'class_ability_poisonweapon_damage_per_rank' AND ABS(`value` - 5) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.19 WHERE `key` = 'class_ability_runeblade_chance' AND ABS(`value` - 0.15) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.08 WHERE `key` = 'class_ability_savageblows_percent_per_rank' AND ABS(`value` - 0.06) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.105 WHERE `key` = 'class_ability_soultether_base' AND ABS(`value` - 0.1) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.085 WHERE `key` = 'class_ability_soultether_step' AND ABS(`value` - 0.075) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.22 WHERE `key` = 'class_ability_spellblade_chance' AND ABS(`value` - 0.2) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.07 WHERE `key` = 'class_ability_sundermark_chance_base' AND ABS(`value` - 0.05) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.06 WHERE `key` = 'class_ability_sundermark_chance_step' AND ABS(`value` - 0.05) < 1e-9;
UPDATE `config_properties_double` SET `value` = 11 WHERE `key` = 'class_ability_taunt_duration' AND ABS(`value` - 10) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.095 WHERE `key` = 'class_ability_withering_percent_per_rank' AND ABS(`value` - 0.08) < 1e-9;
