/* Generated by `ACE.Content.Tools configdefaults --write --migration-name=...`.

   WHY THIS FILE EXISTS - see the generator's stock paragraph in
   ACE.Content.Tools/ConfigDefaults/ConfigDefaultsGenerator.cs: a persisted
   ace_shard.config_properties_* row wins over the code default, so changing a default in source
   alone never reaches a shard that already has a row for that key.

   NOTE, 2026-10-01. The header originally written on this file (2026-09-30) said that mechanism
   was INVERTED and that the code default won at boot. That was true only between PR #1451 and
   the fix on branch fix/config-precedence-boot-merge: #1451 gave Initialize's boot merge the
   live reload's ShouldSkipReload guard, which discarded the persisted row for every key with a
   code default. Initialize's boot merge now passes applyOverModified: true, so row precedence is
   restored and the stock paragraph above is accurate again. The UPDATE below is load-bearing on
   any shard that already carries a row for this key.

   THE GUARD DELIBERATELY LEAVES HAND-TUNED ROWS ALONE. Each UPDATE below only touches a row
   whose current value still equals the OLD default this migration is moving away from. A row
   an operator has since hand-tuned to some other value (via /modifydouble or similar) does not
   match that guard and is left untouched - this migration is about rows that are still sitting
   on the old code default, not about overwriting deliberate configuration.

   RE-RUNNING IS A NO-OP. Once a row has been moved to the new default, its value no longer
   matches the guard's old-value condition, so applying this file again (or against a shard
   that never had the key at all, in which case the WHERE clause simply matches zero rows)
   changes nothing. No marker table or applied-updates bookkeeping is needed for that reason.

   A HAND-ADDED OR ON THE GUARD IS ALLOWED when the repo owner rules that some other specific
   tuned value should also move to the new default - add `OR <condition-on-value>` inside the
   guard's parentheses for that one statement, with a comment above it citing the ruling and
   its date. Do not do this without an explicit owner ruling; the default posture is to leave
   tuned rows alone. */

UPDATE `config_properties_double` SET `value` = 0.0833 WHERE `key` = 'class_ability_empoweredsummons_percent_per_rank' AND ABS(`value` - 0.115) < 1e-9;
