/* Generated by `ACE.Content.Tools configdefaults --write --migration-name=...`.

   WHY THIS FILE EXISTS. PropertyManager.LoadDefaultProperties calls ModifyBool/ModifyDouble/
   ModifyLong/ModifyString for every code default on every boot, and each call marks the entry
   Modified, so the first background flush (every 5 minutes) writes EVERY code default to
   ace_shard.config_properties_* as a row on that shard. From then on the persisted row wins
   over the code default (PropertyManager.LoadPropertiesFromDB runs after LoadDefaultProperties
   and overwrites the in-memory cache), so simply changing a `new Property<T>(default, ...)`
   value in source never reaches a shard that already has a row for that key. This file moves
   the persisted rows forward to match the new code defaults below.

   THE GUARD DELIBERATELY LEAVES HAND-TUNED ROWS ALONE. Each UPDATE below only touches a row
   whose current value still equals the OLD default this migration is moving away from. A row
   an operator has since hand-tuned to some other value (via /modifydouble or similar) does not
   match that guard and is left untouched - this migration is about rows that are still sitting
   on the old code default, not about overwriting deliberate configuration.

   RE-RUNNING IS A NO-OP. Once a row has been moved to the new default, its value no longer
   matches the guard's old-value condition, so applying this file again (or against a shard
   that never had the key at all, in which case the WHERE clause simply matches zero rows)
   changes nothing. No marker table or applied-updates bookkeeping is needed for that reason.

   A HAND-ADDED OR ON THE GUARD IS ALLOWED when the repo owner rules that some other specific
   tuned value should also move to the new default - add `OR <condition-on-value>` inside the
   guard's parentheses for that one statement, with a comment above it citing the ruling and
   its date. Do not do this without an explicit owner ruling; the default posture is to leave
   tuned rows alone. */

/* OWNER RULING, 2026-09-13: prod's Acid Proc row is hand-tuned to 0.08 (neither the old nor the
   new code default), and the owner ruled it should move to the new 0.3 default anyway. The OR
   below is the hand-added exception documented above - it does not change the guard for any
   other statement in this file. */
UPDATE `config_properties_double` SET `value` = 0.3 WHERE `key` = 'class_ability_acidproc_chance_base' AND (ABS(`value` - 0.25) < 1e-9 OR ABS(`value` - 0.08) < 1e-9);
UPDATE `config_properties_double` SET `value` = 0.06 WHERE `key` = 'class_ability_attackspeed_percent_per_rank' AND ABS(`value` - 0.05) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.015 WHERE `key` = 'class_ability_bloodlust_percent_per_rank' AND ABS(`value` - 0.01) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.1 WHERE `key` = 'class_ability_bloodprice_damage_r1' AND ABS(`value` - 0.08) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.2 WHERE `key` = 'class_ability_bloodprice_damage_r2' AND ABS(`value` - 0.16) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.3 WHERE `key` = 'class_ability_bloodprice_damage_r3' AND ABS(`value` - 0.24) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.1 WHERE `key` = 'class_ability_eagleeye_percent_per_rank' AND ABS(`value` - 0.04) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.08 WHERE `key` = 'class_ability_echocast_chance_base' AND ABS(`value` - 0.06) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.08 WHERE `key` = 'class_ability_echocast_chance_step' AND ABS(`value` - 0.06) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.1 WHERE `key` = 'class_ability_elementalrend_chance_base' AND ABS(`value` - 0.08) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.08 WHERE `key` = 'class_ability_elementalrend_chance_step' AND ABS(`value` - 0.06) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.1 WHERE `key` = 'class_ability_flatcastspeed_percent_per_rank' AND ABS(`value` - 0.05) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.08 WHERE `key` = 'class_ability_parry_percent_per_rank' AND ABS(`value` - 0.05) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.15 WHERE `key` = 'class_ability_pocketsand_chance_base' AND ABS(`value` - 0.1) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.15 WHERE `key` = 'class_ability_pocketsand_chance_step' AND ABS(`value` - 0.1) < 1e-9;
UPDATE `config_properties_double` SET `value` = 40 WHERE `key` = 'class_ability_pocketsand_magnitude' AND ABS(`value` - 30) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.012 WHERE `key` = 'class_ability_resonance_per_stack_r1' AND ABS(`value` - 0.02) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.018 WHERE `key` = 'class_ability_resonance_per_stack_r2' AND ABS(`value` - 0.03) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.024 WHERE `key` = 'class_ability_resonance_per_stack_r3' AND ABS(`value` - 0.04) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.6 WHERE `key` = 'class_ability_sanguine_ward_absorb_r1' AND ABS(`value` - 0.5) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.9 WHERE `key` = 'class_ability_sanguine_ward_absorb_r2' AND ABS(`value` - 0.75) < 1e-9;
UPDATE `config_properties_double` SET `value` = 1.2 WHERE `key` = 'class_ability_sanguine_ward_absorb_r3' AND ABS(`value` - 1) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.75 WHERE `key` = 'class_ability_sanguine_ward_selfcost_r1' AND ABS(`value` - 0.8) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.55 WHERE `key` = 'class_ability_sanguine_ward_selfcost_r2' AND ABS(`value` - 0.65) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.35 WHERE `key` = 'class_ability_sanguine_ward_selfcost_r3' AND ABS(`value` - 0.5) < 1e-9;
UPDATE `config_properties_double` SET `value` = 0.14 WHERE `key` = 'class_ability_spellstorm_chance' AND ABS(`value` - 0.1) < 1e-9;
