/* Generated by `ACE.Content.Tools configdefaults --write --migration-name=...`.

   WHY THIS FILE EXISTS. PropertyManager.LoadDefaultProperties calls ModifyBool/ModifyDouble/
   ModifyLong/ModifyString for every code default on every boot, and each call marks the entry
   Modified, so the first background flush (every 5 minutes) writes EVERY code default to
   ace_shard.config_properties_* as a row on that shard. From then on the persisted row wins
   over the code default (PropertyManager.LoadPropertiesFromDB runs after LoadDefaultProperties
   and overwrites the in-memory cache), so simply changing a `new Property<T>(default, ...)`
   value in source never reaches a shard that already has a row for that key. This file moves
   the persisted rows forward to match the new code defaults below.

   THE GUARD DELIBERATELY LEAVES HAND-TUNED ROWS ALONE. Each UPDATE below only touches a row
   whose current value still equals the OLD default this migration is moving away from. A row
   an operator has since hand-tuned to some other value (via /modifydouble or similar) does not
   match that guard and is left untouched - this migration is about rows that are still sitting
   on the old code default, not about overwriting deliberate configuration.

   RE-RUNNING IS A NO-OP. Once a row has been moved to the new default, its value no longer
   matches the guard's old-value condition, so applying this file again (or against a shard
   that never had the key at all, in which case the WHERE clause simply matches zero rows)
   changes nothing. No marker table or applied-updates bookkeeping is needed for that reason.

   A HAND-ADDED OR ON THE GUARD IS ALLOWED when the repo owner rules that some other specific
   tuned value should also move to the new default - add `OR <condition-on-value>` inside the
   guard's parentheses for that one statement, with a comment above it citing the ruling and
   its date. Do not do this without an explicit owner ruling; the default posture is to leave
   tuned rows alone. */

UPDATE `config_properties_long` SET `value` = 3 WHERE `key` = 'bluespire_ladder_d1_reward' AND `value` = 6;
UPDATE `config_properties_long` SET `value` = 4 WHERE `key` = 'bluespire_ladder_d2_reward' AND `value` = 9;
UPDATE `config_properties_long` SET `value` = 5 WHERE `key` = 'bluespire_ladder_d3_reward' AND `value` = 13;
UPDATE `config_properties_long` SET `value` = 6 WHERE `key` = 'bluespire_ladder_d4_reward' AND `value` = 16;
UPDATE `config_properties_long` SET `value` = 7 WHERE `key` = 'bluespire_ladder_d5_reward' AND `value` = 20;
UPDATE `config_properties_long` SET `value` = 10 WHERE `key` = 'bluespire_ladder_d6_reward' AND `value` = 26;
