using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Numerics;
using System.Text;

using log4net;

using ACE.Common;
using ACE.Common.Extensions;
using ACE.Database;
using ACE.Entity;
using ACE.Entity.Enum;
using ACE.Entity.Enum.Properties;
using ACE.Entity.Models;
using ACE.Server.Entity;
using ACE.Server.Entity.Actions;
using ACE.Server.Managers;
using ACE.Server.Network;
using ACE.Server.Network.GameEvent.Events;
using ACE.Server.Network.GameMessages.Messages;
using ACE.Server.Network.Sequence;
using ACE.Server.Network.Structure;
using ACE.Server.Physics;
using ACE.Server.Physics.Animation;
using ACE.Server.Physics.Common;
using ACE.Server.Physics.Util;
using ACE.Server.WorldObjects.Managers;

using Landblock = ACE.Server.Entity.Landblock;
using Position = ACE.Entity.Position;

namespace ACE.Server.WorldObjects
{
    /// <summary>
    /// Base Object for Game World
    /// </summary>
    public abstract partial class WorldObject : IActor
    {
        private static readonly ILog log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        /// <summary>
        /// If this object was created from a weenie (and not a database biota), this is the source.
        /// You should never manipulate these values. You should only reference these values in extreme cases.
        /// </summary>
        public Weenie Weenie { get; }

        /// <summary>
        /// This is object property overrides that should have come from the shard db (or init to defaults of object is new to this instance).
        /// You should not manipulate these values directly. To manipulate this use the exposed SetProperty and RemoveProperty functions instead.
        /// </summary>
        public Biota Biota { get; }

        /// <summary>
        /// This is just a wrapper around Biota.Id
        /// </summary>
        public ObjectGuid Guid { get; }

        public PhysicsObj PhysicsObj { get; protected set; }

        public ObjectDescriptionFlag ObjectDescriptionFlags { get; protected set; }

        public SequenceManager Sequences { get; } = new SequenceManager();

        public virtual float ListeningRadius { get; protected set; } = 5f;

        /// <summary>
        /// Should only be adjusted by Landblock -- default is null
        /// </summary>
        public Landblock CurrentLandblock { get; internal set; }

        public bool IsBusy { get; set; }
        public bool IsShield { get => CombatUse != null && CombatUse == ACE.Entity.Enum.CombatUse.Shield; }
        // ValidLocations is bugged for some older two-handed weapons, still contains MeleeWeapon instead of TwoHanded?
        //public bool IsTwoHanded { get => CurrentWieldedLocation != null && CurrentWieldedLocation == EquipMask.TwoHanded; }
        public bool IsTwoHanded => WeaponSkill == Skill.TwoHandedCombat;
        public bool IsBow { get => DefaultCombatStyle != null && (DefaultCombatStyle == CombatStyle.Bow || DefaultCombatStyle == CombatStyle.Crossbow); }
        public bool IsAtlatl { get => DefaultCombatStyle != null && DefaultCombatStyle == CombatStyle.Atlatl; }
        public bool IsAmmoLauncher { get => IsBow || IsAtlatl; }
        public bool IsThrownWeapon { get => DefaultCombatStyle != null && DefaultCombatStyle == CombatStyle.ThrownWeapon; }
        public bool IsRanged { get => IsAmmoLauncher || IsThrownWeapon; }
        public bool IsCaster { get => DefaultCombatStyle != null && (DefaultCombatStyle == CombatStyle.Magic); }

        public EmoteManager EmoteManager;
        public EnchantmentManagerWithCaching EnchantmentManager;

        // todo: move these to a base projectile class
        public WorldObject ProjectileSource { get; set; }
        public WorldObject ProjectileTarget { get; set; }

        public WorldObject ProjectileLauncher { get; set; }
        public WorldObject ProjectileAmmo { get; set; }

        public bool HitMsg;     // FIXME: find a better way to do this for projectiles

        // PROTOTYPE: multi-shot's extra targets are hit instantly (see Creature_Missile.GetMultiShotTargets) -
        // this flags a purely visual projectile (ProjectileTarget intentionally left null so
        // ProjectileCollisionHelper never applies damage for it) so it doesn't also spam a
        // "hit the environment" message when its cosmetic flight ends.
        public bool IsCosmeticProjectile;

        /// <summary>
        /// WaffleACE fork: this object was generated by Landblock's sky-decor spawner from a
        /// sky_decor_region row. A RUNTIME field on purpose, never a biota property - the object must
        /// leave no trace in any database, and a property would both persist and have to be cleaned up.
        ///
        /// Its ONE load-bearing job is the persistence guard: IsDynamicThatShouldPersistToShard refuses to
        /// save a flagged object (WorldObject_Database.cs). Landblock's own destroy and count paths also
        /// test it, but only as defence in depth over the list they already keep - the flag is not how
        /// they FIND these objects.
        /// </summary>
        public bool IsSkyDecor;

        /// <summary>
        /// WaffleACE fork: this object was placed in code by a one-shot spawner and is owned by nobody, so
        /// it must never be written to the shard. A RUNTIME field for the same reason IsSkyDecor is one -
        /// the object leaves no trace in any database, so there is nothing to clean up later - and it is
        /// read in exactly one place, the persistence guard IsDynamicThatShouldPersistToShard.
        ///
        /// WHY IT IS NEEDED AT ALL. A death spawn (DeathSpawner, PropertyInt 9070) has no generator and it
        /// stands on an ORDINARY PERSISTENT landblock, so neither of the two structural protections other
        /// hand-spawners lean on applies: Landblock.SaveDB's IsEphemeral early return never fires there,
        /// and the "generated by a generator" exclusion does not match. Without this flag a shell-swap add
        /// still standing when the landblock unloaded would be saved, would then take Landblock.Unload's
        /// RemoveWorldObjectInternal arm rather than Destroy, and would walk back into the world on every
        /// later activation of that landblock - a monster nobody killed anything to summon, forever.
        /// </summary>
        public bool IsTransientSpawn;

        public WorldObject Wielder;

        public WorldObject() { }

        /// <summary>
        /// A new biota will be created taking all of its values from weenie.
        /// </summary>
        protected WorldObject(Weenie weenie, ObjectGuid guid)
        {
            Weenie = weenie;
            Biota = ACE.Entity.Adapter.WeenieConverter.ConvertToBiota(weenie, guid.Full, false, true);
            Guid = guid;

            InitializePropertyDictionaries();
            SetEphemeralValues();
            InitializeGenerator();
            InitializeHeartbeats();

            CreationTimestamp = (int)Time.GetUnixTime();
        }

        /// <summary>
        /// Restore a WorldObject from the database.
        /// Any properties tagged as Ephemeral will be removed from the biota.
        /// </summary>
        protected WorldObject(Biota biota)
        {
            Biota = biota;
            Guid = new ObjectGuid(Biota.Id);

            biotaOriginatedFromDatabase = true;

            InitializePropertyDictionaries();
            SetEphemeralValues();
            InitializeGenerator();
            InitializeHeartbeats();
        }

        public bool BumpVelocity { get; set; }

        /// <summary>
        /// Initializes a new default physics object
        /// </summary>
        public virtual void InitPhysicsObj()
        {
            //Console.WriteLine($"InitPhysicsObj({Name} - {Guid})");

            var defaultState = CalculatedPhysicsState();

            if (!(this is Creature))
            {
                var isDynamic = Static == null || !Static.Value;
                var setupTableId = SetupTableId;

                // TODO: REMOVE ME?
                // Temporary workaround fix to account for ace spawn placement issues with certain hooked objects.
                if (this is Hook)
                {
                    var hookWeenie = DatabaseManager.World.GetCachedWeenie(WeenieClassId);
                    setupTableId = hookWeenie.GetProperty(PropertyDataId.Setup) ?? SetupTableId;
                }
                // TODO: REMOVE ME?

                PhysicsObj = PhysicsObj.makeObject(setupTableId, Guid.Full, isDynamic);
            }
            else
            {
                PhysicsObj = new PhysicsObj();
                PhysicsObj.makeAnimObject(SetupTableId, true);
            }

            PhysicsObj.set_object_guid(Guid, Location?.Instance ?? 0);

            PhysicsObj.set_weenie_obj(new WeenieObject(this));

            PhysicsObj.SetMotionTableID(MotionTableId);

            PhysicsObj.SetScaleStatic(ObjScale ?? 1.0f);

            PhysicsObj.State = defaultState;

            // PropertyBool.IgnoreInitialClamp (fork): far-visible scenery skips ObjectMaint's 112.5 m
            // initial-visibility clamp. Cached on the PhysicsObj because the clamp sites run inside the
            // per-player visibility pass, where a property-dictionary lookup per object would be wasted.
            // Never honoured on creatures: the clamp is what keeps monster/player create storms bounded.
            PhysicsObj.IgnoreInitialClamp = !(this is Creature) && IgnoreInitialClamp;

            // PropertyBool.SpawnAtExactPosition (fork, 9069): skip the spawn placement adjustment. Honoured
            // only on a Stuck object (a Creature must also be AiImmobile and NpcLooksLikeObject) - see
            // ExactPlacementStatic and PhysicsObj.ExactPlacement.
            PhysicsObj.ExactPlacement = ExactPlacementStatic;

            if (SpawnAtExactPosition && ExactPlacementRefusal is string refusal)
                WarnExactPlacementIgnoredOnce(WeenieClassId, Name, refusal);

            //if (creature != null) AllowEdgeSlide = true;

            if (BumpVelocity)
                PhysicsObj.Velocity = new Vector3(0, 0, 0.5f);
        }

        public bool AddPhysicsObj()
        {
            if (PhysicsObj.CurCell != null)
                return false;

            AdjustDungeon(Location);

            // exclude linkspots from spawning
            if (WeenieClassId == 10762) return true;

            var cell = LScape.get_landcell(Location.Cell, Location.Instance);
            if (cell == null)
            {
                PhysicsObj.DestroyObject();
                PhysicsObj = null;
                return false;
            }

            PhysicsObj.Position.ObjCellID = cell.ID;

            var location = new Physics.Common.Position();
            location.ObjCellID = cell.ID;
            location.Frame.Origin = Location.Pos;
            location.Frame.Orientation = Location.Rotation;

            var success = PhysicsObj.enter_world(location, Location.Instance);

            if (!success || PhysicsObj.CurCell == null)
            {
                PhysicsObj.DestroyObject();
                PhysicsObj = null;
                //Console.WriteLine($"AddPhysicsObj: failure: {Name} @ {cell.ID.ToString("X8")} - {Location.Pos} - {Location.Rotation} - SetupID: {SetupTableId.ToString("X8")}, MTableID: {MotionTableId.ToString("X8")}");
                return false;
            }

            //Console.WriteLine($"AddPhysicsObj: success: {Name} ({Guid})");
            SyncLocation();

            SetPosition(PositionType.Home, new Position(Location));

            return true;
        }

        public void SyncLocation()
        {
            Location.LandblockId = new LandblockId(PhysicsObj.Position.ObjCellID);

            // skip ObjCellID check when updating from physics
            // TODO: update to newer version of ACE.Entity.Position
            Location.PositionX = PhysicsObj.Position.Frame.Origin.X;
            Location.PositionY = PhysicsObj.Position.Frame.Origin.Y;
            Location.PositionZ = PhysicsObj.Position.Frame.Origin.Z;

            Location.Rotation = PhysicsObj.Position.Frame.Orientation;
        }

        private void InitializePropertyDictionaries()
        {
            if (Biota.PropertiesEnchantmentRegistry == null)
                Biota.PropertiesEnchantmentRegistry = new Collection<PropertiesEnchantmentRegistry>();
        }

        private void SetEphemeralValues()
        { 
            ObjectDescriptionFlags = ObjectDescriptionFlag.Attackable;

            EmoteManager = new EmoteManager(this);
            EnchantmentManager = new EnchantmentManagerWithCaching(this);

            if (Placement == null)
                Placement = ACE.Entity.Enum.Placement.Resting;

            if (MotionTableId != 0)
            {
                CurrentMotionState = new Motion(MotionStance.Invalid);

                // PropertyFloat.MotionSpeed: playback rate for the idle cycle. The create packet sends
                // ForwardSpeed only when it differs from 1.0, so leaving the default alone is a no-op.
                var motionSpeed = GetProperty(PropertyFloat.MotionSpeed);
                if (motionSpeed.HasValue && motionSpeed.Value > 0)
                    CurrentMotionState.MotionState.ForwardSpeed = (float)motionSpeed.Value;
            }
        }

        /// <summary>
        /// This will be true when teleporting
        /// </summary>
        public bool Teleporting { get; set; } = false;

        public bool HasGiveOrRefuseEmoteForItem(WorldObject item, out PropertiesEmote emote)
        {
            // NPC refuses this item, with a custom response
            var refuseItem = EmoteManager.GetEmoteSet(EmoteCategory.Refuse, null, null, item.WeenieClassId);
            if (refuseItem != null)
            {
                emote = refuseItem;
                return true;
            }            

            // NPC accepts this item
            var giveItem = EmoteManager.GetEmoteSet(EmoteCategory.Give, null, null, item.WeenieClassId);
            if (giveItem != null)
            {
                emote = giveItem;
                return true;
            }

            emote = null;
            return false;
        }

        /// <summary>
        /// Returns TRUE if this object has wo in VisibleTargets list
        /// </summary>
        public bool IsVisibleTarget(WorldObject wo)
        {
            if (PhysicsObj == null || wo.PhysicsObj == null)
                return false;

            // note: VisibleTargets is only maintained for monsters and combat pets
            return PhysicsObj.ObjMaint.VisibleTargetsContainsKey(wo.PhysicsObj.ID);
        }

        //public static PhysicsObj SightObj = PhysicsObj.makeObject(0x02000124, 0, false, true);     // arrow

        /// <summary>
        /// Returns TRUE if this object has direct line-of-sight visibility to input object
        /// </summary>
        public bool IsDirectVisible(WorldObject wo)
        {
            if (PhysicsObj == null || wo.PhysicsObj == null)
                return false;

            var SightObj = PhysicsObj.makeObject(0x02000124, 0, false, true);

            SightObj.State |= PhysicsState.Missile;

            var startPos = new Physics.Common.Position(PhysicsObj.Position);
            var targetPos = new Physics.Common.Position(wo.PhysicsObj.Position);

            if (PhysicsObj.GetBlockDist(startPos, targetPos) > 1)
                return false;

            // set to eye level
            startPos.Frame.Origin.Z += PhysicsObj.GetHeight() - SightObj.GetHeight();
            targetPos.Frame.Origin.Z += wo.PhysicsObj.GetHeight() - SightObj.GetHeight();

            var dir = Vector3.Normalize(targetPos.Frame.Origin - startPos.Frame.Origin);
            var radsum = PhysicsObj.GetPhysicsRadius() + SightObj.GetPhysicsRadius();
            startPos.Frame.Origin += dir * radsum;

            SightObj.CurCell = PhysicsObj.CurCell;
            SightObj.ProjectileTarget = wo.PhysicsObj;

            // perform line of sight test
            var transition = SightObj.transition(startPos, targetPos, false);

            SightObj.DestroyObject();

            if (transition == null) return false;

            // check if target object was reached
            var isVisible = transition.CollisionInfo.CollideObject.FirstOrDefault(c => c.ID == wo.PhysicsObj.ID) != null;
            return isVisible;
        }

        public bool IsDirectVisible(Position pos)
        {
            if (PhysicsObj == null)
                return false;

            var SightObj = PhysicsObj.makeObject(0x02000124, 0, false, true);

            SightObj.State |= PhysicsState.Missile;

            var startPos = new Physics.Common.Position(PhysicsObj.Position);
            var targetPos = new Physics.Common.Position(pos);

            if (PhysicsObj.GetBlockDist(startPos, targetPos) > 1)
                return false;

            // set to eye level
            startPos.Frame.Origin.Z += PhysicsObj.GetHeight() - SightObj.GetHeight();
            targetPos.Frame.Origin.Z += SightObj.GetHeight();

            var dir = Vector3.Normalize(targetPos.Frame.Origin - startPos.Frame.Origin);
            var radsum = PhysicsObj.GetPhysicsRadius() + SightObj.GetPhysicsRadius();
            startPos.Frame.Origin += dir * radsum;

            SightObj.CurCell = PhysicsObj.CurCell;
            SightObj.ProjectileTarget = PhysicsObj;

            // perform line of sight test
            var transition = SightObj.transition(targetPos, startPos, false);

            SightObj.DestroyObject();

            if (transition == null) return false;

            // check if target object was reached
            var isVisible = transition.CollisionInfo.CollideObject.FirstOrDefault(c => c.ID == PhysicsObj.ID) != null;
            return isVisible;
        }

        public bool IsMeleeVisible(WorldObject wo)
        {
            if (PhysicsObj == null || wo.PhysicsObj == null)
                return false;

            var startPos = new Physics.Common.Position(PhysicsObj.Position);
            var targetPos = new Physics.Common.Position(wo.PhysicsObj.Position);

            PhysicsObj.ProjectileTarget = wo.PhysicsObj;

            // perform line of sight test
            var transition = PhysicsObj.transition(startPos, targetPos, false);

            PhysicsObj.ProjectileTarget = null;

            if (transition == null) return false;

            // check if target object was reached
            var isVisible = transition.CollisionInfo.CollideObject.FirstOrDefault(c => c.ID == wo.PhysicsObj.ID) != null;
            return isVisible;
        }

        public bool IsProjectileVisible(WorldObject proj)
        {
            if (!(this is Creature) || (Ethereal ?? false))
                return true;

            if (PhysicsObj == null || proj.PhysicsObj == null)
                return false;

            var startPos = new Physics.Common.Position(proj.PhysicsObj.Position);
            var targetPos = new Physics.Common.Position(PhysicsObj.Position);

            // set to eye level
            targetPos.Frame.Origin.Z += PhysicsObj.GetHeight() - proj.PhysicsObj.GetHeight();

            var prevTarget = proj.PhysicsObj.ProjectileTarget;
            proj.PhysicsObj.ProjectileTarget = PhysicsObj;

            // perform line of sight test
            var transition = proj.PhysicsObj.transition(startPos, targetPos, false);

            proj.PhysicsObj.ProjectileTarget = prevTarget;

            if (transition == null) return false;

            // check if target object was reached
            var isVisible = transition.CollisionInfo.CollideObject.FirstOrDefault(c => c.ID == PhysicsObj.ID) != null;
            return isVisible;
        }



        // ******************************************************************* OLD CODE BELOW ********************************
        // ******************************************************************* OLD CODE BELOW ********************************
        // ******************************************************************* OLD CODE BELOW ********************************
        // ******************************************************************* OLD CODE BELOW ********************************
        // ******************************************************************* OLD CODE BELOW ********************************
        // ******************************************************************* OLD CODE BELOW ********************************
        // ******************************************************************* OLD CODE BELOW ********************************

        public MoveToState LastMoveToState { get; set; }

        public Position RequestedLocation { get; set; }

        /// <summary>
        /// Flag indicates if RequestedLocation should be broadcast to other players
        /// - For AutoPos packets, this is set to TRUE
        /// - For MoveToState packets, this is set to FALSE
        /// </summary>
        public bool RequestedLocationBroadcast { get; set; }

        ////// Logical Game Data
        public ContainerType ContainerType
        {
            get
            {
                if (WeenieType == WeenieType.Container)
                    return ContainerType.Container;
                else if (RequiresPackSlot)
                    return ContainerType.Foci;
                else
                    return ContainerType.NonContainer;
            }
        }

        public string DebugOutputString(WorldObject obj)
        {
            var sb = new StringBuilder();

            sb.AppendLine("ACE Debug Output:");
            sb.AppendLine("ACE Class File: " + GetType().Name + ".cs");
            sb.AppendLine("Guid: " + obj.Guid.Full + " (0x" + obj.Guid.Full.ToString("X") + ")");

            sb.AppendLine("----- Private Fields -----");
            foreach (var prop in obj.GetType().GetFields(System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance).OrderBy(field => field.Name))
            {
                if (prop.GetValue(obj) == null)
                    continue;

                sb.AppendLine($"{prop.Name.Replace("<", "").Replace(">k__BackingField", "")} = {prop.GetValue(obj)}");
            }

            sb.AppendLine("----- Public Properties -----");
            foreach (var prop in obj.GetType().GetProperties().OrderBy(property => property.Name))
            {
                if (prop.GetValue(obj, null) == null)
                    continue;

                switch (prop.Name.ToLower())
                {
                    case "guid":
                        sb.AppendLine($"{prop.Name} = {obj.Guid.Full} (GuidType.{obj.Guid.Type.ToString()})");
                        break;
                    case "descriptionflags":
                        sb.AppendLine($"{prop.Name} = {ObjectDescriptionFlags.ToString()}" + " (" + (uint)ObjectDescriptionFlags + ")");
                        break;
                    case "weenieflags":
                        var weenieFlags = CalculateWeenieHeaderFlag();
                        sb.AppendLine($"{prop.Name} = {weenieFlags.ToString()}" + " (" + (uint)weenieFlags + ")");
                        break;
                    case "weenieflags2":
                        var weenieFlags2 = CalculateWeenieHeaderFlag2();
                        sb.AppendLine($"{prop.Name} = {weenieFlags2.ToString()}" + " (" + (uint)weenieFlags2 + ")");
                        break;
                    case "itemtype":
                        sb.AppendLine($"{prop.Name} = {obj.ItemType.ToString()}" + " (" + (uint)obj.ItemType + ")");
                        break;
                    case "creaturetype":
                        sb.AppendLine($"{prop.Name} = {obj.CreatureType.ToString()}" + " (" + (uint)obj.CreatureType + ")");
                        break;
                    case "containertype":
                        sb.AppendLine($"{prop.Name} = {obj.ContainerType.ToString()}" + " (" + (uint)obj.ContainerType + ")");
                        break;
                    case "usable":
                        sb.AppendLine($"{prop.Name} = {obj.ItemUseable.ToString()}" + " (" + (uint)obj.ItemUseable + ")");
                        break;
                    case "radarbehavior":
                        sb.AppendLine($"{prop.Name} = {obj.RadarBehavior.ToString()}" + " (" + (uint)obj.RadarBehavior + ")");
                        break;
                    case "physicsdescriptionflag":
                        var physicsDescriptionFlag = CalculatedPhysicsDescriptionFlag();
                        sb.AppendLine($"{prop.Name} = {physicsDescriptionFlag.ToString()}" + " (" + (uint)physicsDescriptionFlag + ")");
                        break;
                    case "physicsstate":
                        var physicsState = PhysicsObj.State;
                        sb.AppendLine($"{prop.Name} = {physicsState.ToString()}" + " (" + (uint)physicsState + ")");
                        break;
                    //case "propertiesspellid":
                    //    foreach (var item in obj.PropertiesSpellId)
                    //    {
                    //        sb.AppendLine($"PropertySpellId.{Enum.GetName(typeof(Spell), item.SpellId)} ({item.SpellId})");
                    //    }
                    //    break;
                    case "validlocations":
                        sb.AppendLine($"{prop.Name} = {obj.ValidLocations}" + " (" + (uint)obj.ValidLocations + ")");
                        break;
                    case "currentwieldedlocation":
                        sb.AppendLine($"{prop.Name} = {obj.CurrentWieldedLocation}" + " (" + (uint)obj.CurrentWieldedLocation + ")");
                        break;
                    case "priority":
                        sb.AppendLine($"{prop.Name} = {obj.ClothingPriority}" + " (" + (uint)obj.ClothingPriority + ")");
                        break;
                    case "radarcolor":
                        sb.AppendLine($"{prop.Name} = {obj.RadarColor}" + " (" + (uint)obj.RadarColor + ")");
                        break;
                    case "location":
                        sb.AppendLine($"{prop.Name} = {obj.Location.ToLOCString()}");
                        break;
                    case "destination":
                        sb.AppendLine($"{prop.Name} = {obj.Destination.ToLOCString()}");
                        break;
                    case "instantiation":
                        sb.AppendLine($"{prop.Name} = {obj.Instantiation.ToLOCString()}");
                        break;
                    case "sanctuary":
                        sb.AppendLine($"{prop.Name} = {obj.Sanctuary.ToLOCString()}");
                        break;
                    case "home":
                        sb.AppendLine($"{prop.Name} = {obj.Home.ToLOCString()}");
                        break;
                    case "portalsummonloc":
                        sb.AppendLine($"{prop.Name} = {obj.PortalSummonLoc.ToLOCString()}");
                        break;
                    case "houseboot":
                        sb.AppendLine($"{prop.Name} = {obj.HouseBoot.ToLOCString()}");
                        break;
                    case "lastoutsidedeath":
                        sb.AppendLine($"{prop.Name} = {obj.LastOutsideDeath.ToLOCString()}");
                        break;
                    case "linkedlifestone":
                        sb.AppendLine($"{prop.Name} = {obj.LinkedLifestone.ToLOCString()}");
                        break;                    
                    case "channelsactive":
                        sb.AppendLine($"{prop.Name} = {(Channel)obj.GetProperty(PropertyInt.ChannelsActive)}" + " (" + (uint)obj.GetProperty(PropertyInt.ChannelsActive) + ")");
                        break;
                    case "channelsallowed":
                        sb.AppendLine($"{prop.Name} = {(Channel)obj.GetProperty(PropertyInt.ChannelsAllowed)}" + " (" + (uint)obj.GetProperty(PropertyInt.ChannelsAllowed) + ")");
                        break;
                    case "playerkillerstatus":
                        sb.AppendLine($"{prop.Name} = {obj.PlayerKillerStatus}" + " (" + (uint)obj.PlayerKillerStatus + ")");
                        break;
                    default:
                        sb.AppendLine($"{prop.Name} = {prop.GetValue(obj, null)}");
                        break;
                }
            }

            sb.AppendLine("----- Property Dictionaries -----");

            foreach (var item in obj.GetAllPropertyBools())
                sb.AppendLine($"PropertyBool.{Enum.GetName(typeof(PropertyBool), item.Key)} ({(int)item.Key}) = {item.Value}");
            foreach (var item in obj.GetAllPropertyDataId())
                sb.AppendLine($"PropertyDataId.{Enum.GetName(typeof(PropertyDataId), item.Key)} ({(int)item.Key}) = {item.Value}");
            foreach (var item in obj.GetAllPropertyFloat())
                sb.AppendLine($"PropertyFloat.{Enum.GetName(typeof(PropertyFloat), item.Key)} ({(int)item.Key}) = {item.Value}");
            foreach (var item in obj.GetAllPropertyInstanceId())
                sb.AppendLine($"PropertyInstanceId.{Enum.GetName(typeof(PropertyInstanceId), item.Key)} ({(int)item.Key}) = {item.Value}");
            foreach (var item in obj.GetAllPropertyInt())
                sb.AppendLine($"PropertyInt.{Enum.GetName(typeof(PropertyInt), item.Key)} ({(int)item.Key}) = {item.Value}");
            foreach (var item in obj.GetAllPropertyInt64())
                sb.AppendLine($"PropertyInt64.{Enum.GetName(typeof(PropertyInt64), item.Key)} ({(int)item.Key}) = {item.Value}");
            foreach (var item in obj.GetAllPropertyString())
                sb.AppendLine($"PropertyString.{Enum.GetName(typeof(PropertyString), item.Key)} ({(int)item.Key}) = {item.Value}");

            sb.AppendLine("\n");

            return sb.ToString().Replace("\r", "");
        }

        public void QueryHealth(Session examiner)
        {
            float healthPercentage = 1f;

            if (this is Creature creature)
                healthPercentage = (float)creature.Health.Current / creature.Health.MaxValue;

            var updateHealth = new GameEventUpdateHealth(examiner, Guid.Full, healthPercentage);
            examiner.Network.EnqueueSend(updateHealth);
        }

        public void QueryItemMana(Session examiner)
        {
            float manaPercentage = 1f;
            uint success = 0;

            if (ItemCurMana != null && ItemMaxMana != null)
            {
                manaPercentage = (float)ItemCurMana / (float)ItemMaxMana;
                success = 1;
            }

            if (success == 0) // according to retail PCAPs, if success = 0, mana = 0.
                manaPercentage = 0;

            var updateMana = new GameEventQueryItemManaResponse(examiner, Guid.Full, manaPercentage, success);
            examiner.Network.EnqueueSend(updateMana);
        }


        public void EnqueueBroadcastPhysicsState()
        {
            if (PhysicsObj != null)
            {
                if (!Visibility)
                    EnqueueBroadcast(new GameMessageSetState(this, PhysicsObj.State));
                else
                {
                    if (this is Player player && player.CloakStatus == CloakStatus.On)
                    {
                        var ps = PhysicsObj.State;
                        ps &= ~PhysicsState.Cloaked;
                        ps &= ~PhysicsState.NoDraw;
                        player.Session.Network.EnqueueSend(new GameMessageSetState(this, PhysicsObj.State));
                        EnqueueBroadcast(false, new GameMessageSetState(this, ps));
                    }
                    else
                        EnqueueBroadcast(new GameMessageSetState(this, PhysicsObj.State));
                }
            }
        }

        public void EnqueueBroadcastUpdateObject()
        {
            EnqueueBroadcast(new GameMessageUpdateObject(this));
        }

        public virtual void OnCollideObject(WorldObject target)
        {
            // thrown weapons
            if (ProjectileTarget == null) return;

            ProjectileCollisionHelper.OnCollideObject(this, target);
        }

        public virtual void OnCollideObjectEnd(WorldObject target)
        {
            // empty base
        }

        public virtual void OnCollideEnvironment()
        {
            // thrown weapons
            if (ProjectileTarget == null) return;

            ProjectileCollisionHelper.OnCollideEnvironment(this);
        }

        public void ApplyVisualEffects(PlayScript effect, float speed = 1)
        {
            if (CurrentLandblock != null)
                PlayParticleEffect(effect, Guid, speed);
        }

        // plays particle effect like spell casting or bleed etc..
        public void PlayParticleEffect(PlayScript effectId, ObjectGuid targetId, float speed = 1)
        {
            EnqueueBroadcast(new GameMessageScript(targetId, effectId, speed));
        }

        public void ApplySoundEffects(Sound sound, float volume = 1)
        {
            if (CurrentLandblock != null)
                PlaySoundEffect(sound, Guid, volume);
        }

        public void PlaySoundEffect(Sound soundId, ObjectGuid targetId, float volume = 1)
        {
            EnqueueBroadcast(new GameMessageSound(targetId, soundId, volume));
        }

        public virtual void OnGeneration(WorldObject generator)
        {
            //Console.WriteLine($"{Name}.OnGeneration()");

            EmoteManager.OnGeneration();

            // WaffleACE world events: the one seam where an object a GENERATOR put into the world can be
            // seen at birth. A roster weenie carrying generator profiles is itself a generator (both
            // WorldObject constructors call InitializeGenerator), so an event-spawned monster silently
            // spawns children on the landblock tick; those children never pass through
            // WorldEventSpawner.Adopt, are in no held list, and GeneratorDestruct.Undef/Nothing leaves them
            // standing when the parent is destroyed at Finish. Hooked HERE rather than by a WorldObject
            // subclass because this fork never subclasses WorldObject (WorldObjectFactory switches on
            // WeenieType only) and an add can be any type, Creature or item.
            //
            // Deliberately last: an unforeseen throw here must not cost the emote above, and the manager's
            // own first line is a bare static field read that returns immediately when no run exists.
            WorldEvents.WorldEventManager.OnGeneratedIntoWorld(this, generator);
        }

        public virtual bool EnterWorld()
        {
            if (Location == null)
                return false;

            // Bluespire ladder rung 6 (PropertyBool 9063 BluespireCrowdScaled): crowd scaling resolves at
            // each creature's OWN spawn moment, which is the same pattern the world-event waves use. It has
            // to run here and not in the constructor, because the count is scoped by landblock instance and
            // Location is what carries that; and it has to run BEFORE the object reaches a landblock, so no
            // save and no client create packet ever sees a half-scaled creature. The cost on every other
            // spawn in the game is these two type tests plus one property read inside TryApply.
            //
            // PLAYER IS EXCLUDED EXPLICITLY, because Player derives from Creature and this method is on the
            // login and teleport paths as well as the monster-spawn path. Nothing today sets PropertyBool
            // 9063 on a character, so this is hardening rather than a fix - but if anything ever did, crowd
            // scaling would rewrite a player's Health.StartingValue and add DamageRating to them, and a
            // health rescale on a live character is not something a content typo should be able to reach.
            if (this is Creature crowdScaledCreature && !(crowdScaledCreature is Player))
                ACE.Server.Entity.BluespireCrowdScaling.TryApply(crowdScaledCreature);

            if (!LandblockManager.AddObject(this))
                return false;

            if (SuppressGenerateEffect != true)
                ApplyVisualEffects(PlayScript.Create);

            if (Generator != null)
                OnGeneration(Generator);

            //Console.WriteLine($"{Name}.EnterWorld()");

            return true;
        }

        // todo: This should really be an extension method for Position, or a static method within Position or even AdjustPos
        public static void AdjustDungeon(Position pos)
        {
            AdjustDungeonPos(pos);
            AdjustDungeonCells(pos);
        }

        // todo: This should really be an extension method for Position, or a static method within Position or even AdjustPos
        public static bool AdjustDungeonCells(Position pos)
        {
            if (pos == null) return false;

            var landblock = LScape.get_landblock(pos.Cell, pos.Instance);
            if (landblock == null || !landblock.HasDungeon) return false;

            var dungeonID = pos.Cell >> 16;

            var adjustCell = AdjustCell.Get(dungeonID, pos.Instance);
            var cellID = adjustCell.GetCell(pos.Pos);

            if (cellID != null && pos.Cell != cellID.Value)
            {
                pos.LandblockId = new LandblockId(cellID.Value);
                return true;
            }
            return false;
        }

        // todo: This should really be an extension method for Position, or a static method within Position, or even AdjustPos
        public static bool AdjustDungeonPos(Position pos)
        {
            if (pos == null) return false;

            var landblock = LScape.get_landblock(pos.Cell, pos.Instance);
            if (landblock == null || !landblock.HasDungeon) return false;

            var dungeonID = pos.Cell >> 16;

            var adjusted = AdjustPos.Adjust(dungeonID, pos);
            return adjusted;
        }

        /// <summary>
        /// Returns a strike message based on damage type and severity
        /// </summary>
        public virtual string GetAttackMessage(Creature creature, DamageType damageType, uint amount)
        {
            var percent = (float)amount / creature.Health.Base;
            string verb = null, plural = null;
            Strings.GetAttackVerb(damageType, percent, ref verb, ref plural);
            var type = damageType.GetName().ToLower();
            return $"You {verb} {creature.Name} for {amount} points of {type} damage!";
        }

        public Dictionary<PropertyInt, int?> GetProperties(WorldObject wo)
        {
            var props = new Dictionary<PropertyInt, int?>();

            var fields = Enum.GetValues(typeof(PropertyInt)).Cast<PropertyInt>();
            foreach (var field in fields)
            {
                var prop = wo.GetProperty(field);
                props.Add(field, prop);
            }
            return props;
        }

        /// <summary>
        /// Returns the base damage for a weapon
        /// </summary>
        public virtual BaseDamage GetBaseDamage()
        {
            var maxDamage = GetProperty(PropertyInt.Damage) ?? 0;
            var variance = GetProperty(PropertyFloat.DamageVariance) ?? 0;

            return new BaseDamage(maxDamage, (float)variance);
        }

        /// <summary>
        /// Returns the modified damage for a weapon,
        /// with the wielder enchantments taken into account
        /// </summary>
        public BaseDamageMod GetDamageMod(Creature wielder, WorldObject weapon = null)
        {
            var baseDamage = GetBaseDamage();

            if (weapon == null)
                weapon = wielder.GetEquippedWeapon();

            var baseDamageMod = new BaseDamageMod(baseDamage, wielder, weapon);

            return baseDamageMod;
        }

        public bool IsDestroyed { get; private set; }

        /// <summary>
        /// If this is a container or a creature, all of the inventory and/or equipped objects will also be destroyed.<para />
        /// An object should only be destroyed once.
        /// </summary>
        public void Destroy(bool raiseNotifyOfDestructionEvent = true, bool fromLandblockUnload = false)
        {
            if (IsDestroyed)
            {
                //log.WarnFormat("Item 0x{0:X8}:{1} called destroy more than once.", Guid.Full, Name);
                return;
            }

            IsDestroyed = true;

            ReleasedTimestamp = Time.GetUnixTime();

            if (this is Container container)
            {
                foreach (var item in container.Inventory.Values)
                    item.Destroy();
            }

            if (this is Creature creature)
            {
                foreach (var item in creature.EquippedObjects.Values)
                    item.Destroy();
            }

            if (this is Pet pet)
            {
                if (pet.P_PetOwner?.CurrentActivePet == this)
                    pet.P_PetOwner.CurrentActivePet = null;
                else if (pet.P_PetOwner?.SecondaryActivePet == this)   // Summon 2x second slot
                    pet.P_PetOwner.SecondaryActivePet = null;

                if (pet.P_PetDevice?.Pet == Guid.Full)
                {
                    // PetDevice.Pet is a single slot, but Summon 2x puts TWO pets in the world from one
                    // device, so clearing it outright here would drop the "a pet from this device is still
                    // out" signal while the other one is still alive - and that signal is what the
                    // drop/trade/give guards in Player_Inventory + Player_Trade key off. This pet's own slot
                    // was just cleared above, so anything left in either slot is the other pet; re-point the
                    // device at it when it came from this same device, and only clear when none remain.
                    //
                    // Correctness tidying, not an exploit fix: every CombatPet weenie carries Lifespan 43
                    // against the device's flat 45s cooldown, so the survivor is seconds from expiring
                    // anyway and the guard has very little left to protect by this point.
                    var survivor = pet.P_PetOwner?.CurrentActivePet ?? pet.P_PetOwner?.SecondaryActivePet;

                    if (survivor != null && survivor != pet && survivor.P_PetDevice == pet.P_PetDevice)
                        pet.P_PetDevice.Pet = survivor.Guid.Full;
                    else
                        pet.P_PetDevice.Pet = null;
                }
            }

            if (this is Vendor vendor)
            {
                foreach (var wo in vendor.DefaultItemsForSale.Values)
                    wo.Destroy();

                foreach (var wo in vendor.UniqueItemsForSale.Values)
                    wo.Destroy();
            }

            if (this is PersonalVendor mule)
            {
                var summoner = PlayerManager.GetOnlinePlayer(mule.SummonerGuid);

                if (summoner?.CurrentSummonedVendor == this)
                    summoner.CurrentSummonedVendor = null;

                // Mule Vendor task 9: PersonalVendor.Store's setter calls AccountVaultStore.AddWindow/
                // RemoveWindow to pin/unpin the store against the idle-eviction sweep, but nothing calls
                // RemoveWindow when the vendor is destroyed without first being rebound to another store
                // - and Destroy() is the one path every despawn (logout, rot, the distance leash,
                // re-summon) funnels through. Clearing Store here (rather than adding a Destroy override
                // to PersonalVendor, which Destroy is non-virtual for anyway) is what closes that leak;
                // the Store setter's own RemoveWindow call does the actual unpin.
                mule.Store = null;
            }

            if (raiseNotifyOfDestructionEvent)
                NotifyOfEvent(RegenerationType.Destruction);

            if (IsGenerator)
            {
                if (fromLandblockUnload)
                    ProcessGeneratorDestructionDirective(GeneratorDestruct.Destroy, fromLandblockUnload);
                else
                    OnGeneratorDestroy();
            }

            // runs while the projectile's known-players list is still intact, just before the removal broadcast
            // that is limited to it (see SpellProjectile.DeleteFromUntrackedTarget)
            // Landblock.Unload/DestroyAllNonPlayerObjects skip Destroy only for saved biotas; a SpellProjectile never is one (built from a weenie at WorldObjectFactory.cs:138, excluded from SaveDB at WorldObject_Database.cs:208)
            if (this is SpellProjectile spellProjectile)
                spellProjectile.DeleteFromUntrackedTarget();

            CurrentLandblock?.RemoveWorldObject(Guid);

            RemoveBiotaFromDatabase();

            if (Guid.IsDynamic())
                GuidManager.RecycleDynamicGuid(Guid);
        }

        public void FadeOutAndDestroy(bool raiseNotifyOfDestructionEvent = true)
        {
            EnqueueBroadcast(new GameMessageScript(Guid, PlayScript.Destroy));

            var actionChain = new ActionChain();
            actionChain.AddDelaySeconds(1.0f);
            actionChain.AddAction(this, () => Destroy(raiseNotifyOfDestructionEvent));
            actionChain.EnqueueChain();
        }

        public string GetPluralName()
        {
            var pluralName = PluralName;

            if (pluralName == null)
                pluralName = Name.Pluralize();

            return pluralName;
        }

        /// <summary>
        /// Returns TRUE if this object has non-cyclic animations in progress
        /// </summary>
        public bool IsAnimating { get => PhysicsObj != null && PhysicsObj.IsAnimating; }

        /// <summary>
        /// Executes a motion/animation for this object
        /// adds to the physics animation system, and broadcasts to nearby players
        /// </summary>
        /// <returns>The amount it takes to execute the motion</returns>
        public float ExecuteMotion(Motion motion, bool sendClient = true, float? maxRange = null, bool persist = false)
        {
            var motionCommand = motion.MotionState.ForwardCommand;

            if (motionCommand == MotionCommand.Ready)
                motionCommand = (MotionCommand)motion.Stance;

            // run motion command on server through physics animation system
            if (PhysicsObj != null && motionCommand != MotionCommand.Ready)
            {
                var motionInterp = PhysicsObj.get_minterp();

                var rawState = new Physics.Animation.RawMotionState();
                rawState.ForwardCommand = 0;    // always 0? must be this for monster sleep animations (skeletons, golems)
                                                // else the monster will immediately wake back up..
                rawState.CurrentHoldKey = HoldKey.Run;
                rawState.CurrentStyle = (uint)motionCommand;

                if (!PhysicsObj.IsMovingOrAnimating)
                    //PhysicsObj.UpdateTime = PhysicsTimer.CurrentTime - PhysicsGlobals.MinQuantum;
                    PhysicsObj.UpdateTime = PhysicsTimer.CurrentTime;

                motionInterp.RawState = rawState;
                motionInterp.apply_raw_movement(true, true);
            }

            if (persist && PropertyManager.GetBool("persist_movement").Item)
                motion.Persist(CurrentMotionState);

            // hardcoded ready?
            var animLength = MotionTable.GetAnimationLength(MotionTableId, CurrentMotionState.Stance, CurrentMotionState.MotionState.ForwardCommand, motionCommand);
            CurrentMotionState = motion;

            // broadcast to nearby players
            if (sendClient)
                EnqueueBroadcastMotion(motion, maxRange, false);

            return animLength;
        }

        public float ExecuteMotionPersist(Motion motion, bool sendClient = true, float? maxRange = null)
        {
            return ExecuteMotion(motion, sendClient, maxRange, true);
        }

        public void SetStance(MotionStance stance, bool broadcast = true)
        {
            var motion = new Motion(stance);

            if (PropertyManager.GetBool("persist_movement").Item)
                motion.Persist(CurrentMotionState);

            CurrentMotionState = motion;

            if (broadcast)
                EnqueueBroadcastMotion(CurrentMotionState);
        }

        /// <summary>
        /// Returns the relative direction of this creature in relation to target
        /// expressed as a quadrant: Front/Back, Left/Right
        /// </summary>
        public Quadrant GetRelativeDir(WorldObject target)
        {
            var sourcePos = new Vector3(Location.PositionX, Location.PositionY, 0);
            var targetPos = new Vector3(target.Location.PositionX, target.Location.PositionY, 0);
            var targetDir = new AFrame(target.Location.Pos, target.Location.Rotation).get_vector_heading();

            targetDir.Z = 0;
            targetDir = Vector3.Normalize(targetDir);

            var sourceToTarget = Vector3.Normalize(sourcePos - targetPos);

            var dir = Vector3.Dot(sourceToTarget, targetDir);
            var angle = Vector3.Cross(sourceToTarget, targetDir);

            var quadrant = angle.Z <= 0 ? Quadrant.Left : Quadrant.Right;

            quadrant |= dir >= 0 ? Quadrant.Front : Quadrant.Back;

            return quadrant;
        }

        /// <summary>
        /// Returns TRUE if this WorldObject is a generic linkspot
        /// Linkspots are used for things like Houses,
        /// where the portal destination should be populated at runtime.
        /// </summary>
        public bool IsLinkSpot => WeenieType == WeenieType.Generic && WeenieClassName.Equals("portaldestination");

        public const float LocalBroadcastRange = 96.0f;
        public const float LocalBroadcastRangeSq = LocalBroadcastRange * LocalBroadcastRange;

        public SetPosition ScatterPos { get; set; }

        public DestinationType DestinationType;

        public Skill ConvertToMoASkill(Skill skill)
        {
            if (this is Player player)
            {
                if (SkillExtensions.RetiredMelee.Contains(skill))
                    return player.GetHighestMeleeSkill();
                if (SkillExtensions.RetiredMissile.Contains(skill))
                    return Skill.MissileWeapons;
            }

            return skill;
        }

        public void GetCurrentMotionState(out MotionStance currentStance, out MotionCommand currentMotion)
        {
            currentStance = MotionStance.Invalid;
            currentMotion = MotionCommand.Ready;

            if (CurrentMotionState != null)
            {
                currentStance = CurrentMotionState.Stance;

                if (CurrentMotionState.MotionState != null)
                    currentMotion = CurrentMotionState.MotionState.ForwardCommand;
            }
        }

        public virtual void HandleMotionDone(uint motionID, bool success)
        {
            // empty base
        }

        public virtual void OnMoveComplete(WeenieError status)
        {
            // empty base
        }

        public bool IsTradeNote => ItemType == ItemType.PromissoryNote;

        public virtual bool IsAttunedOrContainsAttuned => Attuned >= AttunedStatus.Attuned;

        public virtual bool IsStickyAttunedOrContainsStickyAttuned => Attuned >= AttunedStatus.Sticky;

        public virtual bool IsUniqueOrContainsUnique => Unique != null;

        public virtual List<WorldObject> GetUniqueObjects()
        {
            if (Unique == null)
                return new List<WorldObject>();
            else
                return new List<WorldObject>() { this };
        }

        public bool HasArmorLevel()
        {
            return ArmorLevel > 0;
        }

        public virtual bool IsBeingTradedOrContainsItemBeingTraded(HashSet<ObjectGuid> guidList) => guidList.Contains(Guid);

        public bool IsSocietyArmor => WieldSkillType >= (int)PropertyInt.SocietyRankCelhan && WieldSkillType <= (int)PropertyInt.SocietyRankRadblo;

        public int StructureUnitValue
        {
            get
            {
                var weenie = DatabaseManager.World.GetCachedWeenie(WeenieClassId);
                var weenieValue = weenie?.GetValue() ?? 0;
                var weenieMaxStructure = weenie?.GetMaxStructure() ?? 1;

                var structureUnitValue = weenieValue / weenieMaxStructure;

                return Math.Max(0, structureUnitValue);
            }
        }
    }
}
